name: Python application

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.2"
      - name: Install the project dependencies
        run: poetry install --no-root
      - name: Nuitka compile
        run: poetry run python -m nuitka --standalone --onefile --enable-plugin=pyside6 --assume-yes-for-downloads --disable-console ./microplate-reader.py
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: |
            ./*.exe
            ./icon.png
            ./*.qss
            ./microplate-reader-config.toml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
      - name: GH release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*artifact/*
